SET GLOBAL sql_mode = '';
CREATE DATABASE IF NOT EXISTS db;
CREATE USER IF NOT EXISTS 'db'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON db_srm.* TO 'db'@'%' identified by '1234';
FLUSH PRIVILEGES;

